config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  root to: "posts#index"
  
  #フォローユーザーとフォロワーを取得できるようにネスト
  resources :users do
    get "following" => "users#following"
    get "followers" => "users#followers"
  end
  get 'users/:id' => "users#show_ather"
  resources :relationships, only: [:create, :destroy]

  resources :posts do
    post "likes" => "likes#create"
    delete "likes" => "likes#destroy"
    post "comments" => "comments#create"

  end
  resources :comments, only: [:destroy]
  get 'items/search', to: "items#search"
  resources :items, only: [:destroy, :update]
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    #空欄で投稿できないようにバリデーションをかける
    validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.create(comment_params)
        @comment.save
        render :index
    end
    
    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        render :index
    end
    
    private
        def comment_params
            params.require(:comment).permit(:content, :post_id, :user_id)
        end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<!--コメント入力欄-->
<%= form_with(model: [post, comment], url: post_comments_path(@post) ) do |f| %>
    <%= f.text_area :content, class: "input-mysize" %>
    <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/comments/_index.html.erb
<!--コメントを最初の2件表示する-->
<%= comments.count %>件のコメント
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<% comments.first(2).each do |comment| %>
  <% unless comment.id.nil? %>
    <li class="comment-container">
        <div class="comment-box">
            <div class="comment-text">
                <div class="comment-entry">
                    <%= comment.content %>
                    <% if comment.user == current_user or current_user.admin?%>
                        <%= link_to comment_path(comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                            <i class="fas fa-trash" style="color: black;"></i>
                        <% end %>
                    <% end %>
                </div>
                <span class="comment-date pull-right">
                      <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                </span>
            </div>
        </div>
    </li>
  <% end %>
<% end %>
<!-- コメント内容(3件目以降) ------------------------------------------------------------------>
    <div class="collapse" id="collapseExample">
            <% comments.offset(2).each do |comment| %>
              <% unless comment.id.nil? %>
                <li class="comment-container">
                    <div class="comment-box">
                        <div class="comment-text">
                            <div class="comment-entry">
                                <%= comment.content %>
                                <% if comment.user == current_user or current_user.admin? %>
                                    <%= link_to post_comments_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                                        <i class="fas fa-trash" style="color: black;"></i>
                                    <% end %>
                                <% end %>
                            </div>
                            <span class="comment-date pull-right">
                                  <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                            </span>
                        </div>
                    </div>
                </li>
              <% end %>
            <% end %>
    </div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')