config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  root to: "posts#index"
  
  #フォローユーザーとフォロワーを取得できるようにネスト
  resources :users do
    get "following" => "users#following"
    get "followers" => "users#followers"
  end
  get 'users/:id' => "users#show_ather"
  resources :relationships, only: [:create, :destroy]

  resources :posts do
    post "likes" => "likes#create"
    delete "likes" => "likes#destroy"
    post "comments" => "comments#create"

  end
  resources :comments, only: [:destroy]
  get 'items/search', to: "items#search"
  resources :items, only: [:destroy, :update]
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    #自分をフォローしているユーザー
    #class_nameで参照先のテーブルを指定
    #follower,followingクラスは存在しないクラスだが参照先のテーブルを指定することによって存在しないクラスを参照することを防ぐ。
    belongs_to :follower, class_name: "User"
    
    #自分がフォローしているユーザー
    belongs_to :following, class_name: "User"
    
    #バリデーション
    validates :follower_id, presence: true
    validates :following_id, presence: true
    
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    
    def create
      @user = User.find(params[:following_id])
      current_user.follow(@user)
    end
    #備忘録
    #ここで呼び出している.followメソッドはUserモデルで作成したメソッド。
    #User.find(params[:following_id])で中間テーブルからfollowing_id => user.idを取得し、followメソッドを実行している
    
    def destroy
        @user = User.find(params[:id])
        current_user.unfollow(@user)
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/create.js.erb
$("#follow_form").html("<%= j(render("users//unfollow")) %>");
$("#follower-count_<%= @user.id %>").html('<%= link_to "フォロワー#{ @user.followers.count }人", user_followers_path(@user.id) %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= j(render("users/follow")) %>");
$("#follower-count_<%= @user.id %>").html('<%= link_to "フォロワー#{ @user.followers.count }人", user_followers_path(@user.id) %>');