config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  root to: "posts#index"
  
  #フォローユーザーとフォロワーを取得できるようにネスト
  resources :users do
    get "following" => "users#following"
    get "followers" => "users#followers"
  end
  get 'users/:id' => "users#show_ather"
  resources :relationships, only: [:create, :destroy]

  resources :posts do
    post "likes" => "likes#create"
    delete "likes" => "likes#destroy"
    post "comments" => "comments#create"

  end
  resources :comments, only: [:destroy]
  get 'items/search', to: "items#search"
  resources :items, only: [:destroy, :update]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
         
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_items
  #SNS認証のためのアソシエーション
  has_many :sns_login
  
  #フォロー、フォロワー機能の記述
  
  #中間テーブルとしてfollowing_relationshipsモデルを架空で作成。
  #class:name "Relationship"でRelationshipモデルの外部キーをfollowr_idに指定し、follower_idを参考に、
  #following_relationshipsモデルへアクセスするようにしている。
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  
  #through: :following_relationships で、中間テーブルにfollwoing_relationshipsを指定。
  #その結果、user.followingと打つだけでuserが中間テーブル(following_relationships)を取得し、その1つ1つのfollowing_idから
  #フォローしているUser達を取得できるようになる。
  has_many :following, through: :following_relationships
  
  #こちらも同様で架空のモデルfollowe_relationshipsモデルを作成し、それを中間テーブルに指定している。
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  
  #フォローしているかどうかを確認
  #find_byでフォローしているユーザーのUser.idを取得
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end
  
  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end
  
  #フォロー解除のメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end
  
  #すでにいいねをしているかどうかのチェック
  def already_liked?(post)
   self.likes.exists?(post_id: post.id)
  end
  
  #SNS認証のコールバックの際に呼ばれるメソッド
  def self.from_omniauth(auth)       # snsから取得した、providerとuidを使って、既存ユーザーを検索
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create  # sns認証したことがあればアソシエーションで取得、なければSns_credentialsテーブルにレコード作成
  
    # snsのuser or usersテーブルに対し、SNS認証で取得したメールアドレスが登録済みの場合は、取得 or なければビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?   # userが登録済みの場合：そのままログインするため、snsのuser_idを更新しとく
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }   # user、snsをハッシュで返す(コントローラーがこれを受け取る)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < ApplicationController
  def google_oauth2
    authorization   # コールバック
  end

  def failure
    redirect_to root_path
  end

  private
  # コールバックのメソッド定義
  def authorization   # APIから取得したユーザー情報はrequest.env["omniauth.auth"]に格納されてる
    sns_info = User.from_omniauth(request.env["omniauth.auth"]) 
    #request.env["omniauth.auth"]に格納されている情報は以下の通り
        #provider => プロバイダー(googleなど)
        #uid => プロバイダーの固有の識別子
        #info => ユーザー情報(ハッシュ)
            #name => 表示名
            #email => メールアドレス
            #nickname => ユーザー名(Twitterの@名など)
            #その他いろんな情報が格納されている
    
    @user = sns_info[:user]    # deviseのヘルパーを使うため、＠user に代入(ハッシュ(モデルの返り値)から値を取得)

    if @user.persisted? # ユーザー登録済み(ログイン処理)
      sign_in_and_redirect @user, event: :authentication   # authenticationのcallbackメソッドを呼んで、@user でログイン
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else                # ユーザー未登録(新規登録画面へ遷移)
      @sns_id = sns_info[:sns].id                  # ハッシュ(モデルの返り値)から取得した、認証データを一時的に保持(ユーザー登録ページに渡す)
      render template: new_user_registration_url   # ユーザー登録ページに遷移
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def after_sign_in_path_for(resource)
        redirect_to root
    end
    
    def show
        @post = Post.find(params[:id])
        @user = User.find(params[:id])
    end
    
    def show_ather
        @ather_user = User.find(params[:id])
        pp @ather_user
    end
    
    def index
        @user = User.find(params[:id])
        @users = @user.following
    end
    
    def following
        #@userがフォローしているユーザー
        @user = User.find(params[:id])
        @users = @user.following
    end
    
    def followers
        #@userがフォローされているユーザー
        @user = User.find(params[:id])
        @users = @user.followers
    end
end

app/helpers/user/omniauth_callbacks_helper.rb
module User::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<!--フォローボタン-->
<%= form_with url: relationships_path do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

<!--git Pushテスト-->

app/views/users/_follow_form.html.erb
<!--フォローボタンを表示するフォーム-->

<% if user_signed_in? && @user != current_user %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render "unfollow" %>
        <% else %>
            <%= render "follow" %>
        <% end %>
    </div>
<% end %>
<!--ユーザーがログイン状態で且つ表示しているユーザーがログインユーザーでない場合にフォローボタンを表示している-->
<div>
        <h5 id="follower-count_<%= @user.id %>">
            フォロワー<%= @user.followers.count %>人
        </h5>
</div>

<div>
    <h5 id="following-count_<%= @user.id %>">
        フォロー<%= @user.following.count %>人
    </h5>
</div>

app/views/users/_unfollow.html.erb
<!--フォロー解除ボタン-->
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
    <%= f.submit "フォロー解除", class:"btn btn-outline-secondary" %>
<% end %>

app/views/users/index.html.erb
<h1>フォロー、フォロワー一覧</h1>
<div class="follow">
    <h5>フォロー</h5>
    <% @users.each do |follow| %>
        <p><%= follow.username %></p>
    <% end %>
</div>

app/views/users/show.html.erb
<% if user_signed_in? && @user == current_user %>
  <h1>マイページ</h1>
<% else %>
  <h1>ユーザーページ</h1>
<% end %>

<h1><%= @user.username %></h1>



<div class="user_name">
    <p>ユーザー名:<%= @user.username %></p>
</div>

<div class="follow_btn">
    <%= render "follow_form" %>
</div>

app/views/users/show_ather.html.erb
<h1>ユーザープロフィール</h1>
<p><%= @ather_user.username %></p>