config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  root to: "posts#index"
  
  #フォローユーザーとフォロワーを取得できるようにネスト
  resources :users do
    get "following" => "users#following"
    get "followers" => "users#followers"
  end
  get 'users/:id' => "users#show_ather"
  resources :relationships, only: [:create, :destroy]

  resources :posts do
    post "likes" => "likes#create"
    delete "likes" => "likes#destroy"
    post "comments" => "comments#create"

  end
  resources :comments, only: [:destroy]
  get 'items/search', to: "items#search"
  resources :items, only: [:destroy, :update]
  
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :post_images, dependent: :destroy
    #Postモデルが複数の画像を持てるようにPostImageモデルと紐づける
    has_many :likes, dependent: :destroy
    #PostモデルとLikeモデルを紐づける
    accepts_attachments_for :post_images, attachment: :post_image
    #post_image(_id)をpostのviewにて表示させるための設定
    belongs_to :user
    
    has_many :post_items
    
    has_many :comments, dependent: :destroy
    
    acts_as_taggable
    
    validates :title, presence: true
    validates :content, presence: true
    #タイトル、本文を空欄で投稿させないためのバリデーション設定
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
    before_action :check_admin
    
    def show
        @post =Post.find(params[:id])
    end
    
    def destroy
        @post.destroy
        redirect_to posts_url, notice: "削除完了" 
    end
    
    
    private
    def check_admin
        redirect_to root_path unless current_user.admin?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  def index
    #投稿を新着順で7個
    @posts = Post.order(created_at: :desc).limit(7)
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}")
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    #コメントを新着順で表示するようにする
    @comments = @post.comments.order(created_at: :desc)
    @user = User.find_by(id: @post.user_id)
  end

  def new
    login_check
    @post = Post.new
  end
  
  def login_check
    if current_user.nil?
      redirect_to root_url, alert: "新規投稿するには会員登録、またはログインしてください。"
    end
  end

  def edit
    unless @post.user == current_user
      redirect_to  new_post_path
    end
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id, username: current_user.username))
      if @post.save
        @post_image = PostImage.find_by(post_id:[@post.id])
        tags = Vision.get_image_data(@post_image)
        tags.each do |tag|
          @post_image.post_tags.create(name:tag)
        end
        redirect_to root_path
      else
        render 'posts/new'
      end
  end
  

  def update
      if @post.update(post_params)
        redirect_to @post, notice: "投稿完了"
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "削除完了" 
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :tag_list, post_images_post_images: [])
    end
    
    
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_item.html.erb
<div class="card border mx-auto d-block">
  <div class="card-img-top">
        <%= link_to image_tag(@item.image, size: "150x150"), "item.url" %>
  </div>
  <div class="card-body"><%= @item.name %></div>
  <div class="card-body"><%= @item.price %></div>
</div>

app/views/posts/_post_new.html.erb
<div class="container d-flex flex-column">
    <div class="row visible-xs-block">
        <h2 style="color:#2A3D45;">Recent posts</h2>
    </div>
    
<% if @posts.present? %>
    
    <div class="row justify-content-center">
        <% @posts.each do |post| %>
            <div class="col-sm-3">
                <div class="card mb-4">
                <% post.post_images.first(1).each do |post_image| %>
                    <%= attachment_image_tag post_image, :post_image, size: "100x200" , class:"card-img-top border"%>
                <% end %>
                
                <div class="card-body main">
                    <div class="card-title main">
                        <%= render 'tag_list', tag_list: post.tag_list %>
                    </div>
                    
                    <div class="card-text main">
                        <p style="background-color:#2A3D45;"><%= post.username %>　<%= post.title %></p>
                    </div>
                    
                    <div class="card-text main d-flex justify-content-end">
                        <%= render 'likes/like', post: post %>
                        <%= link_to post_path(post) do %>
                            <i class="far main fa-arrow-alt-circle-right ml-2"></i>
                        <% end %>
                    </div>
                    
                    <div class="card-text main d-flex justify-content-end">
                        <% if PostTag.where(post_image_id: post.post_images.first(1)[0].id) %>
                            <% post.post_images.first(1)[0].post_tags.each do |tag| %>
                                <%= tag.name %>
                            <% end %>
                        <% end %>
                    </div>
                    
                </div>
              
            </div>
            </div>
            
        <% end %>
        
    </div>
    
<% end %>

</div>

app/views/posts/_tag_list.html.erb
<!--@postに格納されているtag_listの情報をtagに格納していき、表示している-->

<% tag_list.each do |tag| %>
    <span class="badge badge-primary mr-1 p-2">
        <%= link_to tag, posts_path(tag_name: tag), class: "text-white" %>
    </span>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= attachment_image_tag @post_image, :post_image %>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if flash[:alert] %>
  <p class="alert alert-warning"><%= flash[:notice] %></p>
<% end %>
<div class="container-fluid">
  <div class="container">
    
    <div id="post_index_new">
      <%= render 'post_new', posts: @posts %>
    </div>
    
  
  </div>
</div>

app/views/posts/item.js.erb
$("#item").html("<%= j(render("posts/item")) %>");

app/views/posts/new.html.erb
<div class="container-fluid d-flex">
  <div class="container col-md-6">
    <div class="container pt-3">
        <div class="menu d-flex">
          <h3>
            <span class="badge mr-3" style="background-color:#2A3D45; color:#ffffff;">新規投稿</span>
          </h3>
        </div>
        
        <%= form_with model: @post,local: true do |f| %>
        <div class="form-group col-10">
          <label for="formGroupExampleInput">タイトル</label>
          <%= f.text_field :title ,class:"form-control"%>
        </div>
        <div class="form-group col-10">
          <label for="formGroupExampleInput2">本文</label>
          <%= f.text_area :content,class:"form-control" %>
        </div>
        <div class="form-group col-10">
          <label for="formGroupExampleInput2">画像</label>
          <%= f.attachment_field :post_images_post_images, multiple: true ,class:"form-control", style:"background-color:#E1DABD; color:#ffffff;"%>
        </div>
        <div class="form-group col-10">
          <label for="formGroupExampleInput2">タグ</label>
          <%= f.text_field :tag_list, value: @post.tag_list.join(','), class: "form-control" %>
        </div>
        <div class="form-group col-10">
          <%= f.submit "投稿" ,class:"btn", style:"background-color:#2A3D45; color:#ffffff;" %>
        </div>
        <% end %>
    </div>
  </div>
  
  <div class="item col-md-6 pt-3">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal3">
      商品を登録する
    </button>
    <div id="item" class="col-md-6 pt-3">
        <% if @item.present? %>
          <% render 'posts/item' %>
        <% else %>
        <% end %>
    </div>
  </div>
  
  
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModal3Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal3Label" style="color:#2A3D45">商品検索</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with url: items_search_path, method: "get" do |f| %>
          <%= f.text_field :keyword %>
          <%= f.submit "検索" ,style:"color:#2A3D45"%>
        <% end %>
        <div id="search_result" class="justify-content-center">
          <% render "/items/search_result" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal" style="background-color:#2A3D45; color:#ffffff;">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.js.erb
$("#post-modal").html("<%= escape_javascript(render 'form') %>")
$("#post-modal").modal("show")

app/views/posts/post.js.erb
$("#post_index_new").html("<%= escape_javascript(render 'posts/post_new', posts: @posts) %>")

app/views/posts/show.html.erb
<div class="container container-fluid">

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>タグ:</strong>
  <%= render 'tag_list', tag_list: @post.tag_list %>
  <!--タグの表示をパーシャルに変更-->
</p>

<p>
  <strong>Username:</strong>
  <%= link_to user_path(@post.user_id) do %>
    <%= @post.username %>
  <% end %>
</p>



<table>
  <td>
  <% if @post.post_images.present? %>
    <% @post.post_images.each do |post_image| %>
      <%= attachment_image_tag post_image, :post_image, size: "200x200" %>
    <% end %>
  <% else %>
    <%= image_tag "/houstagram/app/assets/images/no_image.png", size: "200x200" %>
  <% end %>
    
  </td>
</table>

<div id="show_like_<%= @post.id %>">
  <%= render 'likes/like', post: @post %>
</div>

<div class="comment-area">
  <h3 class="comment-title">コメント</h3>
  <div id="comments_area">
    <%= render partial: "comments/index", locals: {comments: @comments} %>
  </div>
</div>

<% if user_signed_in? %>
  <div class="comment-create">
    <h3 class="comment-title">コメントを投稿する</h3>
    <%= render partial: "comments/form", locals: {comment: @comment, post: @post} %>
  </div>
  <% if @post.user_id == current_user.id or current_user.admin?%>
    <%= link_to '編集', edit_post_path(@post) %>
    <%= link_to '削除', post_path(@post) ,method: :delete %>
  <% end %>
  <% else %>
  
<% end %>


<%= link_to 'Back', posts_path %>

</div>